// Generated from scripts/companion-port-catalogue.json. Do not edit this file directly.
(() => {
    'use strict';

    const core = globalThis.YTKitCore || (globalThis.YTKitCore = {});
    if (core.companionPorts) return;

    const companionPorts = Object.freeze({
        schemaVersion: 1,
        host: "127.0.0.1",
        origin: "http://127.0.0.1:9751-9851",
        primaryPort: 9751,
        ports: Object.freeze([9751,9761,9771,9781,9791,9851]),
        hostPermissions: Object.freeze(["http://127.0.0.1:9751/*","http://127.0.0.1:9761/*","http://127.0.0.1:9771/*","http://127.0.0.1:9781/*","http://127.0.0.1:9791/*","http://127.0.0.1:9851/*"]),
        cspOrigins: Object.freeze(["http://127.0.0.1:9751","http://127.0.0.1:9761","http://127.0.0.1:9771","http://127.0.0.1:9781","http://127.0.0.1:9791","http://127.0.0.1:9851"])
    });
    core.companionPorts = companionPorts;

    if (typeof module !== 'undefined' && module.exports) {
        module.exports = companionPorts;
    }
})();
