'use strict';

// A v1 backup is a bare settings object, so the importer used to accept any
// JSON object as one: `{}`, a package.json, a Watch Feed export. It merged the
// "settings" over the defaults and replaced every setting, then reported
// "Backup imported". And the hand-written reasons the popup did have for a
// refusal were swapped for the generic failure text on the way to the screen.
// These run the shipped importSettings against the real persisted-domain
// service and stop it at the first write.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const persisted = require('../extension/core/persisted-domains');
require('../extension/core/failure-copy');

const popupSource = fs.readFileSync(path.join(__dirname, '..', 'extension', 'popup.js'), 'utf8');
const defaults = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'extension', 'default-settings.json'), 'utf8'));

function slice(startMarker, endMarker) {
    const start = popupSource.indexOf(startMarker);
    assert.ok(start > -1, `${startMarker} must exist`);
    const end = popupSource.indexOf(endMarker, start);
    assert.ok(end > start, `${startMarker} must be followed by ${endMarker}`);
    return popupSource.slice(start, end);
}

function loadImporter() {
    const calls = { statuses: [], writes: [], snapshots: 0 };
    const button = { disabled: false, setAttribute() {}, removeAttribute() {} };
    const sandbox = {
        console: { warn() {}, log() {}, error() {} },
        globalThis: null,
        JSON,
        Object,
        Number,
        String,
        Error,
        Promise,
        t: (_key, fallback) => fallback,
        persistedDomains: persisted,
        importButton: button,
        importFileInput: { value: 'x' },
        showStatus: (message, tone) => calls.statuses.push({ message, tone }),
        loadSettingsImportCatalog: async () => ({ defaults, settingsVersion: 1 }),
        mergeImportedSettingsWithDefaults: (settings) => ({ ...defaults, ...settings }),
        estimateSerializedBytes: () => 0,
        readLocalStorageSnapshot: async () => ({}),
        createCoordinatedSnapshot: async () => { calls.snapshots += 1; return {}; },
        // Stop a genuine backup here: past this point the importer writes.
        writeImportSnapshot: async () => false,
        discardCoordinatedSnapshot: async () => {},
        replaceSettings: async (value) => { calls.writes.push(value); return { settings: value }; },
        storageSet: async (value) => { calls.writes.push(value); },
        storageRemove: async () => {},
        refreshUndoImportVisibility: async () => {},
        requestAnimationFrame: (fn) => fn(),
        setTimeout: (fn) => fn()
    };
    sandbox.globalThis = sandbox;
    sandbox.YTKitCore = globalThis.YTKitCore;
    const source = slice('const RETIRED_SETTING_KEYS = new Set([', '\n]);') + '\n]);\n'
        + slice('function logFailure(context, error) {', '\n// Generated by scripts/i18n-coverage.js')
        + slice('async function importSettings(file) {', '\nasync function undoImportSettings');
    const importSettings = vm.runInNewContext(`(() => {${source}\nreturn importSettings;})()`, sandbox);
    const run = async (payload) => {
        const text = typeof payload === 'string' ? payload : JSON.stringify(payload);
        await importSettings({ size: text.length, text: async () => text });
        return calls.statuses.at(-1);
    };
    return { run, calls };
}

test('a JSON file that is not a backup is refused before anything is written', async () => {
    const wrongFiles = {
        empty: {},
        packageJson: { name: 'astra-deck', version: '4.90.1', scripts: { test: 'node --test' } },
        watchFeedExport: { exportVersion: 1, items: [{ id: 'dQw4w9WgXcQ', title: 'A video' }], current: 0 },
        watchLaterLog: { exportVersion: 1, entries: [{ videoId: 'dQw4w9WgXcQ' }] },
        mostlyForeign: { hideCreateButton: true, name: 'x', version: '1', main: 'index.js' }
    };
    for (const [label, payload] of Object.entries(wrongFiles)) {
        const { run, calls } = loadImporter();
        const status = await run(payload);
        assert.equal(calls.writes.length, 0, `${label}: nothing may be written`);
        assert.equal(calls.snapshots, 0, `${label}: refused before an undo point is staged`);
        assert.equal(status.tone, 'error');
        assert.match(status.message, /isn't an Astra Deck backup, so nothing was imported/, label);
    }
});

test('a genuine v1 settings backup still gets through to the undo point', async () => {
    const { run, calls } = loadImporter();
    // Three of four keys are real only once the retired ones count.
    await run({ hideCreateButton: true, _settingsVersion: 3, cinemaMode: true, mousewheelVolume: true, someUnknownKey: 1 });
    assert.equal(calls.snapshots, 1, 'a bare settings bag with mostly real or retired keys is a v1 backup');
});

test('the popup shows its own reason for a refusal, not the generic failure text', async () => {
    const tooNew = await loadImporter().run({ exportVersion: persisted.BACKUP_EXPORT_VERSION + 1, domains: {} });
    assert.match(tooNew.message, /newer version of Astra Deck\. Update Astra Deck/);

    const notJson = await loadImporter().run('<html>not json</html>');
    assert.match(notJson.message, /^That file is not an Astra Deck backup/);
    assert.doesNotMatch(notJson.message, /Import failed:/, 'the hand-written copy stands alone');

    const nothing = await loadImporter().run({ exportVersion: 2, settings: 'not an object', hiddenVideos: 'nope' });
    assert.match(nothing.message, /holds nothing Astra Deck can import/);
    assert.doesNotMatch(nothing.message, /diagnostic log/, 'that claim is not true here');

    const damaged = await loadImporter().run({ exportVersion: persisted.BACKUP_EXPORT_VERSION, domains: {} });
    assert.match(damaged.message, /^Import failed: The data could not be read/,
        'a structural failure still maps to a cause');
});

test('migrateBackup tags each refusal so a caller can say why', () => {
    const isSettingsKey = (key) => Object.prototype.hasOwnProperty.call(defaults, key);
    assert.throws(() => persisted.migrateBackup({}, { isSettingsKey }), { code: 'not-a-backup' });
    assert.throws(() => persisted.migrateBackup({}), { code: 'not-a-backup' },
        'with no schema to hand, an empty object is still not a backup');
    assert.throws(() => persisted.migrateBackup({ exportVersion: 1, entries: [] }, { isSettingsKey }), { code: 'not-a-backup' });
    assert.throws(() => persisted.migrateBackup({ exportVersion: 99 }), { code: 'backup-too-new' });
    assert.throws(() => persisted.migrateBackup([]), { code: 'bad-format' });
    assert.ok(persisted.migrateBackup({ hideCreateButton: true }, { isSettingsKey }).domains.settings.hideCreateButton);
    assert.ok(persisted.migrateBackup({ exportVersion: 3, settings: {} }, { isSettingsKey }).domains.settings,
        'a declared v2-v4 backup keeps its own settings bag, even an empty one');
});
